// packages/ui-vue/src/ParticipantGrid.vue
<template>
  <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
    <ParticipantTile v-for="p in participants" :key="p.id" :participant="p" />
    <div v-if="!participants.length" class="text-slate-400 text-sm">
      Waiting for participants…
    </div>
  </div>
</template>

<script setup lang="ts">
import ParticipantTile from "./ParticipantTile.vue";

type Participant = {
  id: string;
  label?: string;
  stream?: MediaStream | null;
  connectionState?: RTCPeerConnectionState;
  mutedAudio?: boolean;
  mutedVideo?: boolean;
  isLocal?: boolean;
};

defineProps<{ participants: Participant[] }>();
</script>

// packages/ui-react/src/ParticipantGrid.tsx
import type { FC } from "react";
import type { ParticipantView } from "./types";
import { ParticipantTile } from "./ParticipantTile";

export const ParticipantGrid: FC<{ participants: ParticipantView[] }> = ({
  participants,
}) => {
  return (
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      {participants.map((p) => (
        <ParticipantTile key={p.id} participant={p} />
      ))}
      {participants.length === 0 && (
        <div className="text-slate-400 text-sm">Waiting for participants…</div>
      )}
    </div>
  );
};
